// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Notifications.DataAccess.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    internal class NotificationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Notifications.DataAccess.Entities.NotificationEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Body");

                b.Property<int>("EventType");

                b.Property<string>("Title");

                b.Property<Guid>("UserId");

                b.HasKey("Id");

                b.ToTable("Notifications");
            });

            modelBuilder.Entity("Notifications.DataAccess.Entities.NotificationTemplateEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Body");

                b.Property<int>("EventType");

                b.Property<string>("Title");

                b.HasKey("Id");

                b.ToTable("NotificationTemplates");

                b.HasData(
                    new
                    {
                        Id = new Guid("318f1444-d60e-41ee-a3ea-f14b12370b81"),
                        Body =
                            "Hi {Firstname}, your appointment with {OrganisationName} at {AppointmentDateTime} has been - cancelled for the following reason: {Reason}.",
                        EventType = 0, Title = "Appointment Cancelled"
                    }
                );
            });
#pragma warning restore 612, 618
        }
    }
}